<a href="https://colab.research.google.com/github/AnnuAnuragYadav/iiot4-ml/blob/main/fake_news_detection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
fake = pd.read_csv("/Fake.csv", engine="python", on_bad_lines="skip")
true = pd.read_csv("/True.csv", engine="python", on_bad_lines="skip")

In [ ]:
fake.head()

,title,text,subject,date
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017"
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017"
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017"
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017"
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017"

In [ ]:
true.head()

,title,text,subject,date
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017"
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017"
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017"
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017"
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017"

In [ ]:
fake["label"] = 0
true["label"] = 1

In [ ]:
data = pd.concat([fake, true], axis=0)
data = data.sample(frac=1).reset_index(drop=True)


print(data.shape)
data.head()

(5134, 5)

,title,text,subject,date,label
0,Hillary Clinton Is Apparently Eyeing Elizabet...,While Donald Trump is considering Arizona s fo...,News,"May 13, 2016",0
1,"Donald Trump Jr. wants 'leak' probe, as Congre...",WASHINGTON (Reuters) - President Donald Trump’...,politicsNews,"December 13, 2017",1
2,Trump’s First Major Lie About Hillary Clinton...,If Donald Trump has proven one thing it s that...,News,"May 8, 2016",0
3,FACT: Donald Trump’s Education Plan Would Mas...,"If Donald Trump had his way, 14 percent of Ame...",News,"October 5, 2016",0
4,Actress Rose McGowan Takes On Trump And His ‘...,Best known for her roll in the TV show Charmed...,News,"August 10, 2016",0

In [ ]:


print(fake.columns)
print(true.columns)

Index(['title', 'text', 'subject', 'date', 'label'], dtype='object')
Index(['title', 'text', 'subject', 'date', 'label'], dtype='object')

In [ ]:
data["content"] = data["title"] + " " + data["text"]
data = data[["content", "label"]]
print(data.head())
print(data["label"].value_counts())

                                             content  label
0   Hillary Clinton Is Apparently Eyeing Elizabet...      0
1  Donald Trump Jr. wants 'leak' probe, as Congre...      1
2   Trump’s First Major Lie About Hillary Clinton...      0
3   FACT: Donald Trump’s Education Plan Would Mas...      0
4   Actress Rose McGowan Takes On Trump And His ‘...      0
label
0    4729
1     405
Name: count, dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split

X = data["content"]
y = data["label"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(stop_words="english", max_df=0.7)

X_train_tfidf = vectorizer.fit_transform(X_train)
X_test_tfidf = vectorizer.transform(X_test)

In [ ]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=1000)
model.fit(X_train_tfidf, y_train)

LogisticRegression(max_iter=1000)